Update check-file-contents.yml

diff --git a/.github/workflows/check-file-contents.yml b/.github/workflows/check-file-contents.yml
--- a/.github/workflows/check-file-contents.yml
+++ b/.github/workflows/check-file-contents.yml
@@ -20,7 +20,7 @@ on:
       - '**.py'
 
 jobs:
-  check_files:
+  check-file-contents:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
@@ -37,17 +37,18 @@ jobs:
             echo "$CHANGED_FILES"
             echo ""
 
-          # Check for `logger = logging.getLogger(__name__)` in changed .py files.
-          # The grep command will exit with a non-zero status code if the pattern is not found.
-          # We invert the exit code with ! so the step succeeds if the pattern is NOT found.
-          set +e
-          ! grep -lE 'logger = logging\.getLogger\(__name__\)' $CHANGED_FILES
-          RESULT=$?
-          set -e
+            # Check for `logger = logging.getLogger(__name__)` in changed .py files.
+            # The grep command will exit with a non-zero status code if the pattern is not found.
+            # We invert the exit code with ! so the step succeeds if the pattern is NOT found.
+            set +e
+            ! grep -lE 'logger = logging\.getLogger\(__name__\)' $CHANGED_FILES
+            RESULT=$?
+            set -e
 
-          if [[ $RESULT -ne 0 ]]; then
-            echo "Do not use `logger = logging.getLogger(__name__)`. Use `logger = logging.getLogger('google_adk.' + __name__)` instead."
-            exit 1
+            if [[ $RESULT -ne 0 ]]; then
+              echo "Do not use `logger = logging.getLogger(__name__)`. Use `logger = logging.getLogger('google_adk.' + __name__)` instead."
+              exit 1
+            fi
           fi
 
       - name: Check for import pattern in certain changed Python files
@@ -59,15 +60,16 @@ jobs:
             echo "$CHANGED_FILES"
             echo ""
 
-          # Check for `from __future__ import annotations` in changed .py files.
-          set +e
-          grep -lE 'from __future__ import annotations' $CHANGED_FILES
-          RESULT=$?
-          set -e
+            # Check for `from __future__ import annotations` in changed .py files.
+            set +e
+            grep -lE 'from __future__ import annotations' $CHANGED_FILES
+            RESULT=$?
+            set -e
 
-          if [[ $RESULT -ne 0 ]]; then
-            echo "Always use `from __future__ import annotations`. This allows us to do forward references in type annotations without quotes."
-            exit 1
+            if [[ $RESULT -ne 0 ]]; then
+              echo "Always use `from __future__ import annotations`. This allows us to do forward references in type annotations without quotes."
+              exit 1
+            fi
           fi
 
       - name: Check for import from cli package in certain changed Python files
@@ -79,14 +81,15 @@ jobs:
             echo "$CHANGED_FILES"
             echo ""
 
-          # The grep command will exit with a non-zero status code if the pattern is not found.
-          # We invert the exit code with ! so the step succeeds if the pattern is NOT found.
-          set +e
-          ! grep -lE '^from.*cli\\..*import.*$' $CHANGED_FILES
-          RESULT=$?
-          set -e
+            # The grep command will exit with a non-zero status code if the pattern is not found.
+            # We invert the exit code with ! so the step succeeds if the pattern is NOT found.
+            set +e
+            ! grep -lE '^from.*cli\\..*import.*$' $CHANGED_FILES
+            RESULT=$?
+            set -e
 
-          if [[ $RESULT -ne 0 ]]; then
-            echo "Do not import from the cli package outside of the cli package. If you need to reuse the code elsewhere, please move the code outside of the cli package."
-            exit 1
+            if [[ $RESULT -ne 0 ]]; then
+              echo "Do not import from the cli package outside of the cli package. If you need to reuse the code elsewhere, please move the code outside of the cli package."
+              exit 1
+            fi
           fi
